---
title: "Archiving data"
author: "Cord Huchzermeyer"
date: "2024-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load the required packages
library(here)
library(data.table)
library(jsonlite)
library(ggplot2)

i_am("R/hmp_at_2Hz_and_20Hz_in_IRDs.Rmd") 

tCS_data <- read.csv(here("data", "tCS_data.csv")) |> data.table()
redcap_data <- read.csv(here("data", "redcap_data.csv")) |> data.table()

redcap_data[, patid := record_id]

```

```{r}

select_data <- function(pid, data, type = "RG") {
  data <- data.table(data)
  if (type == "RG") {
    hmp_table <- data[patid == pid & threshold_red > 0, ]
    hmp_table[, x := log10(threshold_red / threshold_green)]
    hmp_table[, y := log10(100 / (threshold_red + threshold_green))]
  } else if (type == "BG") {
    hmp_table <- data[patid == pid & threshold_blue > 0, ]
    hmp_table[, x := log10(threshold_green / threshold_blue)]
    hmp_table[, y := log10(100 / (threshold_blue + threshold_green))]
  }
  class(hmp_table) <- c(class(hmp_table), type)
  return(hmp_table)
}

model_hmp <- function(hmp_table) {
  return_value <- data.frame(type = character(0),
                             frequency = integer(0),
                             coef = double(0))
  
  for (fr in unique(hmp_table$frequency)) {
    hmp_fit <- NULL
    ymin <- min(hmp_table[hmp_table$frequency == fr, ]$y)
    try(hmp_fit <- nls(y ~ hmp::hmp(x, h, v, ymin),
                       data = hmp_table[hmp_table$frequency == fr, ],
                       start = list(h = 0, v = 2)))
    if (!is.null(hmp_fit)) {
      print(coef(hmp_fit)[[1]])
      return_value <- rbind(return_value,
                            data.frame(
                              patid = hmp_table$patid[1],
                              type = class(hmp_table)[length(class(hmp_table))],
                              frequency = fr,
                              h = coef(hmp_fit)[[1]],
                              v = coef(hmp_fit)[[2]]
                            ))
    }
  }
  return(return_value)
}

plot_hmp <-
  function (hmp_table, type = "RG")
  {
    show_function <- data.frame(x = numeric(0), y = numeric(0))
    for (fr in unique(hmp_table$frequency)) {
      hmp_fit <- NULL
      ymin <- min(hmp_table[hmp_table$frequency == fr, ]$y)
      try(hmp_fit <- nls(y ~ hmp::hmp(x, h, v, ymin),
                         data = hmp_table[hmp_table$frequency ==
                                            fr, ],
                         start = list(h = 0, v = 2)))
      if (!is.null(hmp_fit)) {
        show_function <- rbind(
          show_function,
          data.frame(
            x = seq(-1, 1, 0.01),
            y = predict(hmp_fit, data.frame(x = seq(-1, 1, 0.01))),
            frequency = fr,
            h = coef(hmp_fit)[[1]],
            ymin = ymin
          )
        )
      }
    }
    ggplot(hmp_table, aes(x = x, y = y)) +
      geom_point() +
      facet_wrap(~ frequency) +
      geom_line(data = show_function) + geom_label(data = unique(show_function[, 3:5]), aes(
        x = h,
        y = ymin - 0.2,
        label = round(h, 3)
      )) +
      scale_y_continuous("log10 Sensitivity", limits = c(-1, 2)) + theme_bw() +
      scale_x_continuous("log10 C1/C2") +
      ggtitle(class(hmp_table)[length(class(hmp_table))])
  }

hmp_function <-
  function (hmp_table)
  {
    show_function <- data.frame(
      patid = numeric(0),
      x = numeric(0),
      y = numeric(0),
      frequency = numeric(0)
    )
    for (fr in unique(hmp_table$frequency)) {
      hmp_fit <- NULL
      ymin <- min(hmp_table[hmp_table$frequency == fr, ]$y)
      try(hmp_fit <- nls(y ~ hmp::hmp(x, h, v, ymin),
                         data = hmp_table[hmp_table$frequency ==
                                            fr, ],
                         start = list(h = 0, v = 2)))
      if (!is.null(hmp_fit)) {
        print(coef(hmp_fit))
        show_function <- rbind(
          show_function,
          data.frame(
            patid = hmp_table$patid[1],
            x = seq(-1, 1, 0.01),
            y = predict(hmp_fit, data.frame(x = seq(-1, 1, 0.01))),
            frequency = fr
          )
        )
      }
    }
    return(show_function)
  }

apply_hmp <- function(hmp_table) {

  stopifnot(nrow(hmp_table) == 0 | length(unique(hmp_table$patid)) == 1)
  stopifnot(nrow(hmp_table) == 0 | length(unique(hmp_table$frequency)) == 1)
  
  hmp_fit <- NULL
  ymin <- min(hmp_table$y)
  try(hmp_fit <- nls(y ~ hmp::hmp(x, h, v, ymin),
                     data = hmp_table,
                     start = list(h = 0, v = 2)))
  return(list(patid = unique(hmp_table$patid), fit = hmp_fit))
}

apply_linear <- function(hmp_table) {

  stopifnot(nrow(hmp_table) == 0 | length(unique(hmp_table$patid)) == 1)
  stopifnot(nrow(hmp_table) == 0 | length(unique(hmp_table$frequency)) == 1)
  
  hmp_fit <- NULL
  try(hmp_fit <- lm(y ~ x,
                     data = hmp_table))
  return(list(patid = unique(hmp_table$patid), fit = hmp_fit))
}

```


# Fit HMP curves

HMP functions will be fit to the 20Hz green-red and blue-green HMP data.

```{r fit HMP green_red}

hmp_functions_GR <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "RG") |>
      hmp_function()
  })

hmp_functions_GR <- do.call("rbind.data.frame", hmp_functions_GR)

hmp_functions_GR <- merge(hmp_functions_GR, unique(tCS_data[, .(patid, group)]))

```

```{r fit HMP blue_green}

hmp_functions_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "BG") |>
      hmp_function()
  })

hmp_functions_BG <- do.call("rbind.data.frame", hmp_functions_BG)

hmp_functions_BG <- merge(hmp_functions_BG, unique(tCS_data[, .(patid, group)]))

```

# Plot by groups

```{r plot by groups}

ggplot(tCS_data[hmp_type == "green_red", ], aes(x = hmp_x, y = hmp_y)) +
  geom_line(aes(group = factor(patid), color = factor(patid))) +
  facet_grid(frequency ~ group) +
  scale_y_continuous("log10 Sensitivity", limits = c(-1, 2)) + 
  theme_bw() + 
  scale_x_continuous("log10 C1/C2")

ggplot(tCS_data[hmp_type == "blue_green", ], aes(x = hmp_x, y = hmp_y)) +
  geom_line(aes(group = factor(patid), color = factor(patid))) +
  facet_grid(frequency ~ group) +
  scale_y_continuous("log10 Sensitivity", limits = c(-1, 2)) + 
  theme_bw() + 
  scale_x_continuous("log10 C1/C2")


```

# Plot by patients

```{r plot by patients}

ggplot(tCS_data[hmp_type == "green_red", ], aes(x = hmp_x, y = hmp_y)) +
  geom_point(aes(group = factor(frequency), color = factor(frequency))) +
  geom_line(data = hmp_functions_GR, aes(x = x, y = y, color = factor(frequency))) +
  geom_smooth(data = tCS_data[hmp_type == "green_red" & frequency == 2, ],
              method = "lm", aes(color = factor(frequency))) + 
  facet_wrap(~ factor(group) + patid) +
  scale_y_continuous("log10 Sensitivity", limits = c(0, 2)) + 
  theme_bw() + 
  scale_x_continuous("log10 C1/C2") +
  ggtitle("Green vs. Red")

ggsave(here("images", "green_red.png"), height = 8, width = 12)

ggplot(tCS_data[hmp_type == "blue_green", ], aes(x = hmp_x, y = hmp_y)) +
  geom_point(aes(group = factor(frequency), color = factor(frequency))) +
  geom_line(data = hmp_functions_BG, aes(x = x, y = y, color = factor(frequency))) +
  geom_smooth(data = tCS_data[hmp_type == "blue_green" & frequency == 2, ],
              method = "lm", aes(color = factor(frequency))) + 
  facet_wrap(~ factor(group) + patid) +
  scale_y_continuous("log10 Sensitivity", limits = c(0, 2)) + 
  theme_bw() + 
  scale_x_continuous("log10 C1/C2") +
  ggtitle("Blue vs. Green")

ggsave(here("images", "blue_green.png"), height = 8, width = 12)

```



```{r}

green_red <- tCS_data[frequency == 2 & hmp_type == "green_red", 
                         .(log_sens = mean(hmp_y)), by = .(patid)]

green_red <- merge(green_red, redcap_data[, .(patid = record_id, protan = protan_od, deutan = deutan_od)], by = "patid")

blue_green <- tCS_data[frequency == 2 & hmp_type == "blue_green", 
                         .(log_sens = mean(hmp_y)), by = .(patid)]

blue_green <- merge(blue_green, redcap_data[, .(patid = record_id, deutan = deutan_od, tritan = tritan_od)], by = "patid")

ggplot(green_red, aes(x = log_sens, y = deutan)) + 
  geom_point() +
  geom_smooth(method = "lm")

ggplot(blue_green, aes(x = log_sens, y = tritan)) + 
  geom_point() +
  geom_point(aes(y = deutan), color = "green")+ 
  geom_smooth(method = "lm") +
    geom_smooth(aes(y = deutan), color = "green", method = "lm")

```

```{r HMP parameters green_red}

hmp_parameter_GR <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "RG") |>
      model_hmp()
  })

hmp_parameter_GR <- do.call("rbind.data.frame", hmp_parameter_GR)

hmp_parameter_GR <- merge(hmp_parameter_GR, unique(tCS_data[, .(patid, group)]))

hmp_parameter_GR <- merge(hmp_parameter_GR, redcap_data)

ggplot(hmp_parameter_GR, aes(x = factor(group), y = v)) +
  geom_point()

ggplot(hmp_parameter_GR, aes(x = factor(group), y = h)) +
  geom_point()

ggplot(hmp_parameter_GR, aes(x = static_md_od, y = v)) +
  geom_point()

ggplot(hmp_parameter_GR, aes(x = protan_od, y = v)) +
  geom_point()

```

```{r HMP parameters green_red}

hmp_parameter_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "BG") |>
      model_hmp()
  })

hmp_parameter_BG <- do.call("rbind.data.frame", hmp_parameter_BG)

hmp_parameter_BG <- merge(hmp_parameter_BG, unique(tCS_data[, .(patid, group)]))

hmp_parameter_BG <- merge(hmp_parameter_BG, redcap_data)

ggplot(hmp_parameter_BG, aes(x = factor(group), y = v)) +
  geom_point()

ggplot(hmp_parameter_BG, aes(x = factor(group), y = h)) +
  geom_point()

```

# Check model fit

```{r}

hmp_RG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "RG") |>
      apply_model()
  })

fits <- lapply(hmp_RG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)

ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$x)

```

```{r}

hmp_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "BG") |>
      apply_model()
  })

fits <- lapply(hmp_BG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)

ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```
```{r}

linear_RG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 2, ],
                type = "RG") |>
      apply_linear()
  })

fits <- lapply(linear_RG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)


ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```
```{r}

linear_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 2, ],
                type = "BG") |>
      apply_linear()
  })

fits <- lapply(linear_BG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)


ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```
