---
title: "Creating plots for publication"
author: "Cord Huchzermeyer"
date: "2024-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load the required packages
library(here)
library(data.table)
library(jsonlite)
library(ggplot2)
library(kableExtra)
library(officer)
library(flextable)

i_am("R/publication.Rmd")

```

```{r read data}

tCS_data <- read.csv(here("data", "tCS_data.csv")) |> data.table()
redcap_data <- read.csv(here("data", "redcap_data.csv")) |> data.table()
hmp_fits <- read.csv(here("data", "fits.csv")) |> data.table()
parameters <- read.csv(here("data", "parameters.csv")) |> data.table()

```

```{r modify data: factoring}

patient_order_groups <- c(1, 2, 75, 213, 251, 260, 66, 122, 200, 201, 59, 61, 63, 65, 79, 199)
gender <- c(1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1)

tCS_data[, patid := factor(patid, levels = patient_order_groups, ordered = TRUE)]
tCS_data[, group := factor(group, levels = c("normal", "OMD", "STGD", "RP"), ordered = TRUE)]

redcap_data[, patid := factor(record_id, levels = patient_order_groups, ordered = TRUE)]
redcap_data <- merge(redcap_data, 
                     data.table(
                       patid = factor(
                         patient_order_groups, 
                         levels = patient_order_groups, 
                         ordered = TRUE
                       ),
                       gender = factor(
                         gender,
                         levels = c(1, 2),
                         labels = c("male", "female")
                       )
                     ))

parameters[, patid := factor(patid, levels = patient_order_groups, ordered = TRUE)]

```

# Table 1

Add gender.

Is age of 72 correct fo #260?

```{r table 1}

tab1_data <- 
  merge(redcap_data, 
        unique(tCS_data[, .(patid, group)]))[, .(group, 
                                                 age_exam, 
                                                 gender, 
                                                 bcva_od, 
                                                 static_md_od,
                                                 protan_od,
                                                 deutan_od,
                                                 tritan_od)]

tab1_data[, bcva_od := log10(1/bcva_od)]

setkey(tab1_data, group, age_exam)

names(tab1_data) <- 
  c("Dx",
    "Age [yrs]",
    "Gender",
    "logMAR",
    "MD 10deg [dB]",
    "CCT_Protan",
    "CCT_Deutan",
    "CCT_Tritan")


set_flextable_defaults(
  digits = 2,
  decimal.mark = ".",
  big.mark = ",",
  na_str = ""
)

tab1 <-
  flextable(tab1_data) |>
  separate_header() |>
  colformat_double()



doc <- read_docx()
doc <- body_add_flextable(doc, tab1)
print(doc, target = "table1.docx")


```

# Plot HMP curves

```{r plot by patients green_red}

get_group <- function(pid) { 
  tCS_data[patid == pid, group] |>
    unique() |>
    as.character()
}

get_group <- Vectorize(get_group)

ggplot(tCS_data[hmp_type == "green_red", ], aes(x = hmp_x, y = hmp_y)) +
  geom_point(aes(group = factor(frequency), color = factor(frequency))) +
  geom_line(data = hmp_fits[type == "green_red", ], aes(x = x, y = y, color = factor(frequency))) +
  geom_smooth(data = tCS_data[hmp_type == "green_red" & frequency == 2, ],
              method = "lm", aes(color = factor(frequency))) + 
  facet_wrap(~ factor(patid, levels = patient_order_groups, ordered = TRUE), 
             labeller = as_labeller(get_group)) +
  scale_y_continuous(expression(log[10] * " " * Sensitivity), limits = c(0, 2)) +
  scale_x_continuous(expression(log[10] * " " * frac(C[red], C[green])), limits = c(-1.1, 1.1)) +
  theme_bw() + 
  guides(group = "none", color = "none")

ggsave(here("images", "green_red.png"), height = 8, width = 12)
```

```{r plot by patients blue_green}

ggplot(tCS_data[hmp_type == "blue_green", ], aes(x = hmp_x, y = hmp_y)) +
  geom_point(aes(group = factor(frequency), color = factor(frequency))) +
  geom_line(data = hmp_fits[type == "blue_green", ], aes(x = x, y = y, color = factor(frequency))) +
  geom_smooth(data = tCS_data[hmp_type == "blue_green" & frequency == 2, ],
              method = "lm", aes(color = factor(frequency))) + 
  facet_wrap(~ factor(patid, levels = patient_order_groups, ordered = TRUE), 
             labeller = as_labeller(get_group)) +
  scale_y_continuous(expression(log[10] * " " * Sensitivity), limits = c(0, 2)) +
  scale_x_continuous(expression(log[10] * " " * frac(C[green], C[blue])), limits = c(-1.1, 1.1)) +
  theme_bw() + 
  guides(group = "none", color = "none")

ggsave(here("images", "blue_green.png"), height = 8, width = 12)

```

# Plot by groups

```{r plot by groups}

tCS_data[, freq_lab := factor(frequency, levels = c(2, 20), labels = c("2 Hz", "20 Hz"))]

ggplot(na.omit(tCS_data[hmp_type == "green_red", ]),
       aes(
         x = hmp_x,
         y = hmp_y,
         group = factor(patid),
         color = factor(patid)
       )) +
  stat_summary(fun = "mean", geom = "line") +
  facet_grid(freq_lab ~ group) +
  scale_y_continuous(expression(log[10] * " " * Sensitivity), limits = c(0, 2)) +
  theme_bw() +
  scale_x_continuous(expression(log[10] * " " * frac(C[red], C[green])), limits = c(-1.1, 1.1)) +
  guides(color = "none")

ggsave(here("images", "rawGR.png"))

ggplot(na.omit(tCS_data[hmp_type == "blue_green", ]),
       aes(
         x = hmp_x,
         y = hmp_y,
         group = factor(patid),
         color = factor(patid)
       )) +
  stat_summary(fun = "mean", geom = "line") +
  facet_grid(freq_lab ~ group) +
  scale_y_continuous(expression(log[10] * " " * Sensitivity), limits = c(0, 2)) +
  theme_bw() +
  scale_x_continuous(expression(log[10] * " " * frac(C[green], C[blue]))) +
  guides(color = "none")
ggsave(here("images", "rawBG.png"))

```

# Compare parameters

## Luminance

```{r compare luminance}

compare_luminance <- dcast(parameters[, .(patid, type, v)], patid ~ type)
compare_color <- dcast(parameters[, .(patid, type, intercept)], patid ~ type)

ggplot(compare_luminance, aes(x = RG, y = BG)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_abline(slope = 1) +
  theme_bw() +
  scale_x_continuous("Red-Green HMP: v-parameter") +
  scale_y_continuous("Blue-Green HMP: v-parameter")

cor.test(compare_luminance$BG, compare_luminance$RG, method = "spearman")

```

```{r compare color}

compare_color <- dcast(parameters[, .(patid, type, intercept)], patid ~ type)

ggplot(compare_color, aes(x = RG, y = BG)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_abline(slope = 1) +
  theme_bw() +
  scale_x_continuous("Red-Green HMP: intercept") +
  scale_y_continuous("Blue-Green HMP: intercept")


cor.test(compare_color$BG, compare_luminance$RG, method = "spearman")

```

# Compare with clinical parameters

```{r red-green vs. clinical}

clinical_parameters <- merge(redcap_data, parameters[type == "RG", ])

clinical_parameters[, .(patid, deutan_od, v)]

ggplot(clinical_parameters, aes(x = deutan_od, y = static_md_od)) +
  geom_point()

ggplot(clinical_parameters, aes(x = static_md_od, y = v)) +
  geom_point() +
  scale_x_log10()

cor.test(clinical_parameters$static_md_od, clinical_parameters$v, method = "spearman")

ggplot(clinical_parameters, aes(x = deutan_od, y = intercept)) +
  geom_point() +
  scale_x_log10()

cor.test(clinical_parameters$protan_od, clinical_parameters$intercept, method = "spearman")

```

```{r blue-green vs. clinical}

clinical_parameters <- merge(redcap_data, parameters[type == "BG", ])

clinical_parameters[, .(patid, tritan_od, v)]

ggplot(clinical_parameters, aes(x = tritan_od, y = static_md_od)) +
  geom_point()

ggplot(clinical_parameters, aes(x = static_md_od, y = v)) +
  geom_point()

cor.test(clinical_parameters$static_md_od, clinical_parameters$v, method = "spearman")

ggplot(clinical_parameters, aes(x = protan_od, y = intercept)) +
  geom_point()

cor.test(clinical_parameters$tritan_od, clinical_parameters$intercept, method = "spearman")

```

# Check model fit

## HMP models

```{r hmp_residuals green_red at 20Hz}

fits <- lapply(hmp_RG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)

ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$x)

```

```{r hmp_residuals blue_green at 20Hz}

hmp_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 20, ],
                type = "BG") |>
      apply_hmp()
  })

fits <- lapply(hmp_BG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)

ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```

## Linear models

```{r linear residuals green_red at 2Hz}

linear_RG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 2, ],
                type = "RG") |>
      apply_linear()
  })

fits <- lapply(linear_RG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)


ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```

```{r linear residuals blue_green at 2Hz}

linear_BG <-
  lapply(unique(tCS_data$patid), function (x) {
    select_data(pid = x,
                data = tCS_data[frequency == 2, ],
                type = "BG") |>
      apply_linear()
  })

fits <- lapply(linear_BG, function(x) data.table(patid = x$patid, 
                                      x = fitted.values(x$fit), 
                                      y = resid(x$fit))) 

fits <- fits[sapply(fits, function(x) return(ncol(x) == 3))]

fits <- do.call("rbind.data.frame", fits)


ggplot(fits, aes (x = x, y = y)) + 
  geom_point(aes(group = patid)) +
  geom_line(aes(group = patid))

ggplot(fits, aes(x = y)) +
  geom_histogram()

shapiro.test(fits$y)

```

# Analyze REDCap data

```{r}

redcap_data[order(bcva_od), .(bcva_od, protan_od, tritan_od, static_md_od)]

cor(redcap_data$bcva_od, redcap_data$protan_od, method = "spearman", use = "complete.obs")
```

# Tritan

```{r}

redcap_data[, patid := factor(patid)]
hmp_parameters_BG <- merge(hmp_parameters_BG, redcap_data)

ggplot(hmp_parameters_BG, aes(x = h, y = tritan_od)) +
  geom_point(aes(color = group)) +
  geom_smooth(method = "lm")

ggplot(hmp_parameters_BG, aes(x = h, y = static_md_od)) +
  geom_point(aes(color = group)) +
  geom_smooth(method = "lm")

```

# Check for drift in blue LED

```{r}

drift_table <- merge(parameters, unique(tCS_data[, .(patid, date_of_exam)]))
drift_table <- drift_table[date_of_exam != "2021-04-26", ]
drift_table[, date_of_exam := as.POSIXct(date_of_exam)]


ggplot(drift_table, aes(x = date_of_exam, y = h)) +
  geom_point(aes(color = group)) +
  geom_smooth(method = "lm") +
  facet_wrap(~ type)

ggplot(drift_table, aes(x = date_of_exam, y = v)) +
  geom_point(aes(color = group)) +
  geom_smooth(method = "lm") +
  facet_wrap(~ type)

```

